### ISSUE TITLE
4YI: https://github.com/IAIK/jstemplate

### ISSUE THREAD

**Issue by KOLANICH** [ghacksuserjs/TorZillaPrint#40]

**Comment by Thorin-Oakenpants** [comment]
@KOLANICH 

from your comment: `https://github.com/WICG/visual-viewport/issues/63`

![screen](https://user-images.githubusercontent.com/16656956/63530337-cbfe8f00-c4f5-11e9-936e-8dd992658c1a.png)

These all change in real time as you resize your browser or go full screen or maximize. The four non-css ones simply use a window `resize` event listener.

On desktops, this is not a problem. With letterboxing, this is not a problem: even with the slight delay in letterboxing, leaking sizes are you transition from one letterbox size to another is not a leak, or an entropy. And of course with RFP, this is not a problem either.

The problem comes, as you pointed out, on mobiles: where the screen/viewport is the actual device, and things like keyboards eat into that space and provide an exact measurement.

You used to actually see this in Tor Browser when you went full screen / maximized and the yellow warning panel that came down actually eats into the inner window: revealing the height of the warning message (in the past the app language would affect the height, but was patched a long time ago to be a set height for all: a fat 80px or something). This warning will no longer be needed with letterboxing.

For some reason, on 8.5.4 I can't even trigger that warning.

**Comment by Thorin-Oakenpants** [comment]
Right: so thinking about mobile: letterboxing will kick in on the viewport: so keyboard heights will bucketed: I most will be about the same height.

**Comment by KOLANICH** [comment]
>so keyboard heights will bucketed: I most will be about the same height.

The important thing is how exactly is it going to be bucketed. There are 3 options, both are very bad.

1. do real letterboxing. Inacceptable - screen space is too scarce on mobiles.
2. just round the visibleViewport sizes returned by JS to a higher value. Can be easily countermeasured - a malicious webmaster can put some essential website controls to an upper bound of keyboard. Then if user's browser has lied about a keyboard, these controls will go under actual keyboard. Though it may be beneficial - these controls will likely waste screen space.
3. just round the visibleViewport sizes returned by JS to a lower value.  Then the webmaster can create opaque elements, placed to the space claimed to be screened by a keyboard, effectively transforming the situation to 1.

So, IMHO the best action here is to abolish this spec and don't implement it at all.

BTW why don't you discuss this in that issue?

**Comment by Thorin-Oakenpants** [comment]
FYI: I mentioned it here for you, because there is no need to discuss Mozilla internals with other people. LB on mobile is not implemented yet, but can be done: seen it. But for now, this is for Tor Browser on Android to implement AFAIK - there isn't a bugzilla. Not even sure what the trac.tor ticket is TBH. No doubt it will get upstreamed: IDK. Implementation may be different, the threat model is different.

**Comment by Thorin-Oakenpants** [comment]
FYI: I made viewport update in real time as well. It just uses a full sized element on the page and gets it's dimensions

**Comment by KOLANICH** [comment]
1. keyboard size is leaked
2. size of addressbar is leaked
3. neither uMatrix, nor NoScript, nor uBlock have managed to block scripts on file:// scheme. Damn.

**Comment by Thorin-Oakenpants** [comment]
AFAIK, the size of `chrome` (urlbars, etc) is leaked not leaked with RFP, as all external measurements are reported as the inner window

What do extension permissions on file:// have to do with this? I don't follow. File content doesn't run in web content, and you have control over your own files. Extensions also don't have control over other privileged content, such as other extensions. That's just part of the design of web extensions (I guess). I know in the past that with XUL etc uMatrix used to be able to. But it's not a big deal: make sure you choose and vet your extensions

**Comment by KOLANICH** [comment]
>AFAIK, the size of chrome (urlbars, etc) is not leaked with RFP, as all external measurements are reported as the inner window

Do you use Firefox for Android? Could you test?

>What do extension permissions on file:// have to do with this? I don't follow. File content doesn't run in web content, and you have control over your own files. Extensions also don't have control over other privileged content, such as other extensions. That's just part of the design of web extensions (I guess). I know in the past that with XUL etc uMatrix used to be able to. But it's not a big deal: make sure you choose and vet your extensions

It is not about an extension, it is about a `file://` schema. Of course it is often user's decision which file:// URIs to open. But file URIs are usual webpages, they can be used to run web applications without using an HTTP server, so IMHO WebExtensions should work there fully and correctly.

**Comment by Thorin-Oakenpants** [comment]
https://thorin-oakenpants.github.io/testing/kbh.html

Here's my droid opening the page. Note: I have zoomed in so you can see the values etc
![01](https://user-images.githubusercontent.com/16656956/63668466-c4293e00-c7c6-11e9-825c-b0bf74ba7c65.jpg)

When I click into (or out of) the text area, an onfocus event occurs which I track with a boolean. Then as the keyboard opens, this triggers a resize event. In that resize function, as well as recalculating everything, if the boolean is true, I simply compare the previous viewport height with the current one and output the **absolute value** (i.e losing focus returns a negative number: e.g `-716` rather than `716`: so we ignore the negative). 

The resize event is the same as the one on TZP for desktop (except the extra keyboard checking stuff): e.g when you manually resize or zoom or go fullscreen etc. Pinch zooming doesn't seem to trigger this on android, but sometimes the top 4 values did change: e.g when I would click on the text area and the screen zoomed in by itself to the text area. But viewport never changed

Here's the pic (zoomed) when I enter the text area
![02](https://user-images.githubusercontent.com/16656956/63668934-1f0f6500-c7c8-11e9-8f36-21061711c767.jpg)


Note: I have RFP on. And I am so confused with Android screen things (I have a tor ticket in that I don't even understand), that I'll leave it up to sysqrb and Tom

**Comment by Thorin-Oakenpants** [comment]
> Could you test (when one scrolls a page down (by swiping up) the locationbar hides and when one scrolls up it slites to visibility, reducing page viewport size)?

I'll give it a go (have made a note to look at this later). The TZP page screen / window / viewport measurements are all real time (resize event), and the css media ones are automatic too.

I can click the full screen test to get into FS, and then I'll have a play. I still don't even know how to exit FS: the function is meant to exit FS after grabbing details, but doesn't for me on my android. Anyway, the measurements, if affected, should show a difference in real time

> It is not about an extension, it is about a file:// schema. 

You'll have to take that up with Mozilla. AFAIK: file content and web content are not allowed to mix, and file content is not Mozilla's responsibility, IMO.

**Comment by Thorin-Oakenpants** [comment]
> when one scrolls a page down (by swiping up) the locationbar hides and when one scrolls up it slites to visibility,

I can't get this to work. in FS my viewport height is now 1674 (it was 1522) so therefore my urlbar chome is 152 pixels. But I cannot get the urlbar to display regardless of what swiping I do. Maybe I have a weird phone?

**Comment by Thorin-Oakenpants** [comment]
@KOLANICH 

OK, I wiped my droid FF (I actually had a user.js applied there as well) and created a new clean profile. I see now that there is a setting option to hide the toolbar when scrolling down. I had that disabled, not anymore.

The other thing is the full screen test, on desktop it exits FS after grabbing the info, but on droid it doesn't - even though I use two methods. And I could never work out how to exit FS after that - but now I can: when I enter the text field for the keyboard test, FS exits.

---

OK, so I added two tests, to grab the keyboard height, and the toolbar height. I'm relying on a simple delay to grab the measurements, but I could easily tighten that by using a setInterval and repeatedly checking. Code only runs if the OS is android.

I grab the keyboard height in a simple onfocus event for the text field, and allow for whether or not the toolbar was hidden before entering the field. The keyboard "slides" up, affecting the viewport gradually.

I grab the toolbar height in an onscroll event, looking for a higher value than you had when you first loaded the page (which always has the toolbar showing). Scrolling seems to "snap" into place (scroll down really slowly and as the toolbar becomes visible, it doesn't affect the viewport ... until it suddenly does. It's a little iffy ... I can bypass it by slowly scrolling .. but generally speaking, as you scroll up and down like a normal human being, it seems to capture it. I will probably harden it up later using a setInterval

Here's my results: have a play and let me know what you think

![this-is-the-droid-you-were-looking-for](https://user-images.githubusercontent.com/16656956/66123993-d28f2480-e5d2-11e9-8778-2a1883e60a2a.png)

**Comment by Thorin-Oakenpants** [comment]
PS: it's zoom resistant

**Comment by Thorin-Oakenpants** [comment]
@KOLANICH ... just got some info from a Tor Android specialist, who said "The toolbar is always a fixed-height",  so you aren't leaking anything there

**Comment by KOLANICH** [comment]
>The toolbar is always a fixed-height", so you aren't leaking anything there

I am not sure that the locationbar height  will never change in future.

> so you aren't leaking anything there

leak of keyboard height is a serious leak hy itself. BTW, if you really use the keyboard I see on the screenshot on daily basis, here is something better:  https://f-droid.org/en/packages/org.pocketworkstation.pckeyboard/ 

> I'm relying on a simple delay to grab the measurements, but I could easily tighten that by using a setInterval and repeatedly checking. Code only runs if the OS is android.
>I will probably harden it up later using a setInterval
>Here's my results: have a play and let me know what you think

 Current approach confuses keyboard with locationbar. You have latent variables `keyboard_visible`, `toolbar_visible`, `keyboard_height`, `screen_height` and `locationbar_height`, observable variables `viewport_height` (takes values `{screen_height, screen_height - locationbar_height, screen_height - locationbar_height - keyboard_height, screen_height - keyboard_height}`) and `scroll direction` (takes values {-1, 1}) and and constraints on which states have edges to which states. These should be enough to infer the latent variables using the state machine. But if we assume that `keyboard_height > locationbar_height > 0`, then we can just create a set of all possible values of `viewport_height` and sort it. If there are only 4 values, than we know which one corresponds to which state. If there are more, then we can try to do k-means clustering with k=4.

**Comment by Thorin-Oakenpants** [comment]
> I am not sure that the locationbar height will never change in future

But it would change for all users. i.e we can already detect FF version, and users should be up-to-date (latest stable, latest ESR if that's even a thing on Android)

> the other stuff you said

I know virtually nothing about android. All I can do is mess around and prototype. I have noticed that there are several variables: e.g. auto-hiding the toolbar can be enabled/disabled, e.g. when you first load a page it always shows the toolbar, if you enter a text field it forces the toolbar to be visible, and so on. I just fixed my FS test which I added for desktop: I needed to add a delay (in desktop I need to make sure there isn't one).

AFAICT, it's all pretty rock solid (except I could tighten up the keyboard and toolbar with constant checking via a setInterval and return the max value, or something). Some measurements require user gestures: I can't control that, so I can't always get all four values.

Here's what I get when I do the test: it's not about making sure I get them all, for some it's a PoC to show what could leak **if** they do this or that.
- with toolbar: first page load: 1522
- without toolbar via scrolling: 1674 -> 152 toolbar
- FS: 1742 -> reveals the bar at the top of the phone was 68 pixels
- keyboard -> 716

> If there are only 4 values, than we know which one corresponds to which state

I can't guarantee to get all four states. At most I can get only guarantee one value: with the toolbar. If toolbar auto-hide is enabled, then I would probably get the non-toolbar height because they are likely to scroll. But that's it.

**Comment by KOLANICH** [comment]
> i.e we can already detect FF version

We should assumme that adversary cannot. It is one of the goals. In the ideal case adversary gets 0 bits of info and all the browsers look the same for him.

>I can't guarantee to get all four states. 

Certainly. You can ask the user to do them. When using the webapps like email or github these gestures are unavoidable, so it's safe to assumme that if they wanted to get this info, they have already collected it.

**Comment by Thorin-Oakenpants** [comment]
> We should assumme that adversary cannot

Sure. But the point remains that everyone gets the change, if it ever happens. If someone chooses to not update, then that's on them

> Certainly. You can ask the user to do them

Lol. Sure .. let's **assume** then ... this is the exact opposite of what you just said. Let me re-phrase: "on my web page test, I cannot guarantee ..." However, I'm inviting people to **test** the leak as a worst case scenario. In reality, a webpage could cover the entire screen with an element and trick users into gestures, and use other underhanded techniques - I can't do that on the main TZP page (but I could do it on a stand-alone page: except I don't need to). Or like you said, if a site's functionality relies on e.g. text fields they have to use then that's unavoidable.

I'm not even sure if a JS scroll function would reveal the toolbar visible vs not-visible: even if it did, I wouldn't add that to the main TZP page (making it scroll - like https://acatarineu.github.io/fp/devicePixelRatio.html ) - but I could on a stand-alone page

**Comment by Thorin-Oakenpants** [comment]
closing this
we went totally OT 😁 - I've got any remaining issues with android PoCs in my todo list issue


JS attack templates is not a new concept AFAIK
   - here's a [test](https://privacycheck.sec.lrz.de/active/fp_fd/fp_feature_detection.html) using Modernizr
   - here's a [test](https://privacycheck.sec.lrz.de/active/fp_css/fp_css.html) enumeratinng css
   - here's a [test](https://privacycheck.sec.lrz.de/active/fp_cpt/fp_can_play_type.html) checking media stuff
   - I read a paper a while ago: `10.14722-ndss.2019.23155` (don't have a link, only a local copy) - if you want a copy @KOLANICH , I'll email it to you: just let me know

Maybe I'm missing the point here: but I need to craft special (smaller/faster) tests to target what we *know* "can" leak, so 1: we can get entropy/results and 2: decide how to best tackle it and 3: check our methods work when implemented

If users don't fuck with settings/prefs then they shouldn't differ on 99% of all these metrics (e.g canPlayType etc): not that we shouldn't investigate them: e.g there may be subtle differences between platforms or because of graphic cards etc

A template like this is good for finding where we leak entropy, not as an overall fingerprinter

**Comment by KOLANICH** [comment]
>I read a paper a while ago: 10.14722-ndss.2019.23155

Thanks for the info.

>don't have a link

Is it the same as https://www.ndss-symposium.org/wp-content/uploads/2019/02/ndss2019_01B-4_Schwarz_paper.pdf ?

**Comment by Thorin-Oakenpants** [comment]
^ yup, that's the one
