### ISSUE TITLE
audio test

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#58]
With spoofing off: sum returned (for me) is
- `35.7383295930922` [TZP](https://ghacksuserjs.github.io/TorZillaPrint/TorZillaPrint.html#audio) and [CB](https://canvasblocker.kkapsner.de/test/audioTest.html) and [OpenWPM](https://audiofingerprint.openwpm.com/)
- `35.97669053450227` at http://fp.virpo.sk/ (don't ask me why it's not HTTPS)

You can see the audio code here : http://fp.virpo.sk/js/script.js 

Why are they different? Did @ViRPo (Peter Hraška) make a boo boo .. or is he a genius that has something figured out that we haven't - seeing as you based your code on OpenWPM, and I based mine on yours - @kkapsner

**Comment by kkapsner** [comment]
ViRPo is using `setTargetAtTime` instead of setting the values directly which produces slightly different results. Not sure if it increases entropy or not.

**Comment by Thorin-Oakenpants** [comment]
I hope he sees this (last time I pinged him it took months: if I remember correctly he was on holiday), because he did a 500K+ browser fingerprinting test for his thesis, and in small scale testing he made a number of improvements and fixes which got upstreamed to fingerprintjs2 (which he used as the basis for his script)

Maybe that's it: [fpjs2 line 362](https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L362) is using `setValueAtTime` - no idea what it produces as a result, since there demo page is practically locked off to encourage people to sign up

I wonder if we should investigate those two, maybe add them?

**Comment by kkapsner** [comment]
`setValueAtTime` does not change anything for me only `setTargetAtTime` (which makes sense). Also "sine" is used instead of "triangle".

I updated my test page to show the differences.

**Comment by Thorin-Oakenpants** [comment]
I guess I better update the TZP tests. So `delayed` is with or without `setTargetAtTime` ?

**Comment by kkapsner** [comment]
`delayed` is with `setTargetAtTime`.
So `triangle (10000 Hz)` is OpenWPM and `sine (10000 Hz) delayed` is virpo.

**Comment by Thorin-Oakenpants** [comment]
@kkapsner ...
- what is the second copyTest for?
- what is the importance of testing an empty buffer?

so far I have this (the values all match your test page)
![audiostuff](https://user-images.githubusercontent.com/16656956/80866408-007a3b80-8c7e-11ea-9f1e-3f5a8b4c435c.png)

just have to work out how I want to smash that data into some arrays and display it

**Comment by Thorin-Oakenpants** [comment]
also, you used to use window.OfflineAudioContext(`1`, 44100, 44100) but now you use window.OfflineAudioContext(`2`, 44100, 44100) - why's that?

**Comment by kkapsner** [comment]
>     * what is the second copyTest for?

to check that the results are persistent and you get the same result on the second run. So that CB cannot be detected that way.



>     * what is the importance of testing an empty buffer?

This is a known value and should not be faked by CB. Also a way CB could be detected if not covered.


> why's that?

Both channels should return the same results. If they would differ CB could be detected.

**Comment by ViRPo** [comment]
Hmm, if I made any breakthrough discovery, it must have been by accident

I started with OpenWPM code for audio fingerprinting and have a note in my thesis, that I had to adjust the code to make it work on iPhones as well as updated some deprecated JavaScript code in that specific function

I don't have any commit history for audio fingerprint, so I can't really find out what I changed and why

If OpenWPM's code for audio fingerprinting stayed unchanged since 2018, then diffing their and my code could help us reveal what I changed and why
