### ISSUE TITLE
copyFromChannel and getChannelData are given each others hash

### ISSUE THREAD

**Issue by abrahamjuliot** [ghacksuserjs/TorZillaPrint#62]
https://github.com/ghacksuserjs/TorZillaPrint/blob/96746f00f8092754663cea101245bb791964f2b4/js/audio.js#L237

To match the promise, audioCopy should be given hashes[1]. Otherwise, the html hash for copyFromChannel and getChannelData is switched.

```
dom.audioCopy = byteArrayToHex(hashes[1])
dom.audioGet = byteArrayToHex(hashes[0])
```

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot  Nice catch

I actually have a new audio.js here which I need to finish (I better check that one as well), which does more by adding triangle vs sine, delayed vs not, chunks - etc: as per kkapsners tests and discussion we had in #58 

---

On a side-note: I've been slowly adding in more robust error handling. I do not want any silent failures, but also AOPR will actually crash the js. I guess you've been seeing those changes, but it's a work in progress (section by section) - e.g

```js
*##+js(aopr, navigator.userAgent)
*##+js(set, navigator.appCodeName, undefined)
```

![aopr](https://user-images.githubusercontent.com/16656956/84525654-8781f100-accb-11ea-8964-77b189009453.png)

Doing just those two on amiunique trashes the whole test

This includes those `falseFunc` ones. Everything has some entropy value, and where or how the error occurs is part of that: e.g. TypeError vs ReferenceError (vs `undefined` where applicable) - and in each function I just spit out if it's a, b,c, d etc and that becomes part of the hash fingerprint

You've been keeping me busy :) but I don't see how wholesale blocking of APIs helps: for **most** of them it would just make the internet unusable? Right?

Here's what happens when you kill these for the screen section
```js
*##+js(aopr, Element.prototype.getBoundingClientRect)
*##+js(aopr, window.getComputedStyle)
```
![aopr2](https://user-images.githubusercontent.com/16656956/84527250-818d0f80-accd-11ea-96ae-17c21de5733e.png)

I don't actually use that in the hash, but I can detect both behaviors

killing **both** `matchMedia` **and** `getComputedStyle` are required to disrupt the many fallbacks I have in detecting zoom level - which is hard enough as it is, thanks :)

![aopr3](https://user-images.githubusercontent.com/16656956/84527714-e9dbf100-accd-11ea-92ac-25d9fdc4b23f.png)

**Comment by Thorin-Oakenpants** [comment]
fixed in https://github.com/ghacksuserjs/TorZillaPrint/commit/eac22733e90d0ec48eb7f38201dd1b7813157813 👍

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot PS: I just noticed you using `auudio.js` in your repo file name (2 `u`'s) .. is that a typo?

**Comment by abrahamjuliot** [comment]
I have noticed the rubust error handling. Yep, that's probably me throwing all those errors.  This project is the best to test on. 

True, AOPR and blocking APIs is overkill and many scripts catch/handle errors. It creates a terrible experience on many popular sites. I like it only as an aggressive option, but it's only affective if done at random and given a significant timeout between executions.
 
I'm currently testing a custom abort using window.confirm which pauses the execution and then I have ok to allow or cancel to try abort. That way the error is not of necessity consistently thrown. There's also the option to abort by throwing a random common (and misleading) reference or type error that is consistent with browser. Also, if there is a collection of properties that must follow one property in order to create a fingerprint, then there is an option when the property is read: select one of those properties at random and abort when that property is read. This way, the property aborted is never consistent. This is also similar to blocking a set of properties at random. I look at these only as aggressive measures.

**Comment by abrahamjuliot** [comment]
> @abrahamjuliot PS: I just noticed you using `auudio.js` in your repo file name (2 `u`'s) .. is that a typo?

Ha, yes. That's what i get for coding at 1 am.

**Comment by Thorin-Oakenpants** [comment]
> That's what i get for coding at 1 am.

Yup.... been there many a time

> This project is the best to test on

Awesome™ ... I'm guess I'm doing something right then - thanks :)

It's basically just me with help from kkapsner when he has time, and JS isn't my forte, so I've just been plodding along in my spare time. Feel free to help out with things you want added or improved for your testing

> ... aopr etc

I consider this stuff pretty edge case. I'm more concerned with silently failing or scripts crashing. The main purpose of this is to detect results to help beat FPing, not how to linkfy traffic - I mean fingerprints change all the time: user agent is updated, new graphics driver might change canvas or webgl, user adds or removes system fonts etc. And studies have found that's it's still relatively easy to link changing fingerprints.

As for the entropy in e.g. `script blocked [a]` and ``script blocked [b]` etc, linkifying would perhaps only need to parse the ``script blocked` part: same as in canvas, it doesn't need to know the hash, only that it is randomized -> i.e stability in FPs matters, but isn't the be-all end-all: don't get me wrong: a binary choice is still effective

e.g. "There's also the option to abort by throwing a random common (and misleading) reference or type error" - if you look at some of my code, if it's not an error Firefox would normally throw (both name and message), then it's still caught in a final `if`: so throw what ever you like it'll just be caught as `script blocked [d]` or something. I already do this with ReferenceError by only returning the name (because the message is randomized). My handling and output on all this is not exactly consistent, but at some stage I'll get around to that.

What you're talking about is a **poison pill** and to be effective, those need to blend in IMO and be undetectable. So not sure about the aborting, when spoofing can be more effective (ignoring the limitations of extensions)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot 

> There's also the option to abort by throwing a random common (and misleading) reference or type error

While it's not 100% perfect (there are some other `try catches` within some `if` clauses), what I did with the language section's 38 items, is only allow the right error message according to the FF version, otherwise it is treated as script interference

```js
	} catch(e) {
		if (isFF) {
			// standard FF errors
			let msg = ""
			if (item == 5 || item == 36) {
				if (e.message == "Intl.ListFormat is not a constructor" && isVer < 78) {msg = zNS}
			} else if (item == 24) {
				if (e.message == "Intl.RelativeTimeFormat is not a constructor" && isVer < 65) {msg = zNS}
			} else if (item == 25 ) {
				if (e.message == "Intl.RelativeTimeFormat is not a constructor" && isVer < 65) {msg = zNS}
				if (e.message == "rtf.formatToParts is not a function" && isVer > 64 && isVer < 70) {msg = zNS}
			} else if (item == 28 || item == 29) {
				if (e.message == "BigInt is not defined" && isVer < 68) {msg = zNS + " [BigInt]"}
				if (e.message == "can't convert BigInt to number" && isVer > 67 && isVer < 70) {msg = zNS}
			} else if (item == 33) {
				if (e.message == "Intl.RelativeTimeFormat is not a constructor" && isVer < 65) {msg = zNS}
			}
			// script blocking
			if (msg == "") {
				err.push(item +" [unexpected]: "+ e.name + " : " + e.message)
				if (e.name == "ReferenceError") {return zB1
				} else if (e.name == "TypeError") {return zB2
				} else {return zB3}
			} else {
				err.push(item +" [expected]: "+ e.name + " : " + e.message)
			}
			return msg
		} else {
			return "error"
		}
	}
```

and then when I get check the returns
```js
	for (let i=0; i < 38; i++) {
		let result = get_item(i)
		if (result == undefined) {result = zB4}
		if (result == "undefined") {result = zB5}
		res.push(result)
		document.getElementById("ldt"+i).innerHTML = result
	}
```

I only used the error message not the type as well, and I made isVer pretty robust (nothing relies on css, multiple checks for 78 since it's ESR, nothing controlled by a pref, using obscure things), and I'm only really concerned with ESR and current stable (so yeah, you can break the version check for 73 by blocking getComputedStyle - but AFAIC, 73 is history): at the end of the day, if you want to break it, you will: it's a game of whack-a-mole that isn't worth playing from my perspective

How's the 🐈 coming along?

**Comment by abrahamjuliot** [comment]
That is pretty sweet error catch. Looking foward to testing that.

> How's the 🐈 coming along?
lol...it's slow right now. I just finished Rects and am currently implementing Audio. I'm not sure I'm going to release this. It's just an expirement at the moment. I might decide to convert it over to a uBlock Origin scriptlet with options to use local storage to delay randomization up to 8 hours per site. It initially started out as that.

I'm also adding mild protection against native code checks. Similar to above, it's difficult to get near that 100% mark.

If you're interested in using [this](https://github.com/abrahamjuliot/CreepJS/blob/master/hasLiedAPI.js), it exposes many API Function spoof attempts and/or attempts to cover it up. For example, here's a console check for toDataURL:
```
// name must return "toDataURL"
HTMLCanvasElement.prototype.toDataURL.name

// toString() must return "function toDataURL() { [native code] }"
HTMLCanvasElement.prototype.toDataURL.toString()

// toString must strictly equal Function.prototype.toString
HTMLCanvasElement.prototype.toDataURL.toString === Function.prototype.toString

// toString.toString() must return "function toString() { [native code] }"
HTMLCanvasElement.prototype.toDataURL.toString.toString()

toString.toString must strictly equal Function.prototype.toString
HTMLCanvasElement.prototype.toDataURL.toString.toString === Function.prototype.toString
```
I wrote a [protection](url) that passes all the above, but the last check catches it. It's totally a game of whack-a-mole. If I try to counter it, that can be countered with:
```
// must return true
HTMLCanvasElement.prototype.toDataURL.toString.toString.toString === Function.prototype.toString
```
And, there's no end that battle. Fun fun. =)

**Comment by Thorin-Oakenpants** [comment]
reminds me of @kkapsners upcoming for 10x nested iframes

**Comment by Thorin-Oakenpants** [comment]
it's actually a [thing](https://github.com/ghacksuserjs/TorZillaPrint/issues/54#issuecomment-630000685)

**Comment by abrahamjuliot** [comment]
That's amazing. I recently starting using kkapsner's test site. Awesome work.

**Comment by Thorin-Oakenpants** [comment]
This is just another thing I already had on my mind, and I'm not sure how to implement it. I'll add it to my ToDo list so I don't forget. I **think** this is what you're referring to: masking the JS function or call so scripts/extensions can't detect it?

I've read this in papers: one was randomizing extension variables, function names. And I'm aware that extensions can leak these. Another one a PoC that leaks Canvas Defender, from memory: it had something to do with prototype

**Comment by Thorin-Oakenpants** [comment]
this wasn't what I was looking for, but it's close: https://antoinevastel.com/tracking/2018/07/01/eval-canvasdef.html

**Comment by abrahamjuliot** [comment]
Yes, this is very similar. toString reveals the whole function and essentially captures a fingerprint (if the function is left static). Antoine's approach goes further to detect mutations and extract the original function -- that is awesome. I'm looking into that. Since extension content script can run and manipulate the dom at document start, it might be difficult to ensure the mutation observer and the extract function executes before the script is injected.

**Comment by Thorin-Oakenpants** [comment]
Ahhh ... as luck would have it, I came across what I was looking for: it wasn't actually about Canvas Defender (although that was also detectable and I had also read those reports/PoCs in the past) .. it was about Privacy Badger

https://adtechmadness.wordpress.com/2020/03/27/detecting-privacy-badgers-canvas-fp-detection/

**Comment by kkapsner** [comment]
This whole `toString` and detecting changed functions thing is why CanvasBlocker is not available for Chrome - there is no `exportFunction` which protects the addons code:
* an exported function will also be displayed as `[native code]`
* you have your own protected function "scope" (the Xray) so the pages scripts cannot mess with your addons code

> That's amazing. I recently starting using kkapsner's test site. Awesome work.

Thanks - if you have any specific feedback I'm glad to hear about it.

> it's actually a [thing](https://github.com/ghacksuserjs/TorZillaPrint/issues/54#issuecomment-630000685)

Thanks for reminding me... almost forgot about it (over my current work with keepassxc-mail - Thunderbird is a weird place to create addons for at the moment)

**Comment by Thorin-Oakenpants** [comment]
> almost forgot about it

You need a ToDo List .. I have one here for you, with my stuff in it to get you started 😁

**Comment by kkapsner** [comment]
> You need a ToDo List

I have more than one... maybe that's the problem...

Added the nested iframes test: https://canvasblocker.kkapsner.de/test/iframeTest.html
