### ISSUE TITLE
PerformanceTiming API in RFP mode

### ISSUE THREAD

**Issue by earthlng** [ghacksuserjs/TorZillaPrint#77]
FF79+: [1637985](https://bugzilla.mozilla.org/1637985) Reenable the PerformanceTiming API in RFP mode

https://hg.mozilla.org/mozilla-central/rev/0fd90d6f9937

basically a bunch of timings aren't returning 0 anymore, including `loadEventEnd` which you use under "Miscellaneous"

**Comment by Thorin-Oakenpants** [comment]
Thanks. I know about that one :)  .. loadEvenEnd is not RFP notated, it's just a metric. RFP is only applied in FF, and the notated just means you match what RFP is, not that it is actually on since some of them can be changed with prefs (but, just quietly, `getEntries` is RFP unique)

FF82
```
[getEntries*] performance.mark | 1, 27, 27, 1 [RFP] <-- red
performance.now | 69, 83, 98, 12, 24, 37, 50, 63, 76, 90 [RFP] <-- red
[loadEventEnd] performance.timing | not zero
PerformanceNavigationTiming | enabled [RFP]  <-- red
```

FF82 + RFP
```
[getEntries*] performance.mark | 0, 0, 0, 0 [RFP] <- green
performance.now | 100 ms [RFP] <-- green
[loadEventEnd] performance.timing | not zero
PerformanceNavigationTiming | disabled [RFP] <-- green
```

**Comment by Thorin-Oakenpants** [comment]
@earthlng .. this looks interesting: --> https://senglehardt.com/test/dfpi/storage_access_api.html but fucked if I can work out how to interpret some of the results - mentioning because it looks like a very neat test

[1661152](https://bugzilla.mozilla.org/show_bug.cgi?id=1661152) - I don't know if FPI is affected: I have used cookies = 2 for years and have never seen any data or cookies, but then again I also have uBO in medium + uM in nightmare modes - might only be a dPFI thing
